services:
  pgadmin:
    image: 'dpage/pgadmin4:9.7.0'
    container_name: 'pgadmin'
    hostname: 'pgadmin'
    restart: 'unless-stopped'
    ports:
      - '80:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
